routes/web.php
<?php

use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes(['verify' => true]);
Route::get('/', function () {
    $languages = \App\Language::all();
    return view('welcome',compact('languages'));
});

Route::resource("users","UserController");
Route::resource("pages","PageController")->middleware('verified');;
Route::resource("phrases","PhraseController");
Route::resource("sites","SiteController");

Auth::routes();

//Route::get("/read","SiteController@read");
Route::post("/render","PageController@render");
Route::post("/updatephrases","PageController@fetch");
Route::post("/save","PageController@save");


Route::get('/home', 'HomeController@index')->name('home');
Route::post("/sites/{id}/synclanguages","SiteController@syncLanguages");
Route::get("/sites/{id}/selector","SiteController@selectorPage");
Route::post("/sites/{id}/selector","SiteController@selector");

Route::prefix('admin')->group(function () {
    Route::get('/', "AdminController@index");
});

app/User.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',"surname", 'email', 'password', "key"
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function sites()
    {
    	return $this->hasMany("App\Site");
    }

    public function getCreatedAtAttribute($value)
    {
        return Carbon::parse($value)->format("d.m.Y H:i");
    }

    /**
     * Число используемых слов
     *
     * @return int
     */
    public function wordsCount()
    {
        $sites = $this->sites;
        $texts = PhraseLanguage::whereHas("phrase", function ($q) use ($sites) {
            $q->whereHas("page", function ($query) use ($sites) {
                $query->whereIn("site_id", $sites->pluck("id"));
            });
        })->get()->unique("phrase_id")->pluck("value");

        $count = 0;
        foreach ($texts as $text) {
            $c = count(explode(" ", $text));
            if ($text && $c > 0) {
                $count = $count + $c;
            }
        }
        return $count;
    }


    /**
     * Отличаем Админа
     *
     * @return bool
     */
    public function getIsAdminAttribute()
    {
        return $this->id == 1;
    }
}

resources/views/admin/dashboard.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                @include("statuses.success")
                @include("statuses.error")
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item active" aria-current="page">ADMIN</li>
                    </ol>
                </nav>
                <div class="card">
                    <div class="card-header">
                        Dashboard
                    </div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                        @foreach($users as $user)
                            <div class="card card-primary mt-3">
                                <div class="card-header">
                                    {{$user->name}} {{$user->surname}} @if($user->email_verified_at) <span class="badge badge-success">V</span> @endif
                                </div>
                                <div class="card-body">
                                    <p>Email: <span class="text-primary">{{$user->email}}</span></p>
                                    <p>Registered: {{$user->created_at}}</p>
                                    <p>Sites: {{count($user->sites)}}</p>
                                    @if(count($user->sites)>0)
                                        <ul>
                                            @foreach($user->sites as $site)
                                                <li>
                                                    <p>Domain: <strong class="text-success">{{$site->domain}}</strong></p>
                                                    <p>Base language: {{$site->language->name}}</p>
                                                    <p>Translate
                                                        languages: {{$site->languages->pluck("name")->implode(", ")}}</p>
                                                    <ul>
                                                        @foreach($site->pages as $page)
                                                            <li>
                                                                <p>{{$site->domain}}{{$page->url}} <span
                                                                        class="text-muted">{{count($page->phrases)}} phrases</span>
                                                                </p>
                                                            </li>
                                                        @endforeach
                                                    </ul>
                                                </li>
                                            @endforeach
                                        </ul>
                                    @endif
                                </div>
                            </div>
                        @endforeach

                        {{ $users->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection